sudo: false
notifications:
  email:
    on_success: change
    on_failure: always

language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci
